name: Test Streamlit App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test imports
        run: |
          python -c "import streamlit, pandas, numpy, scipy, matplotlib, plotly, seaborn, openpyxl; print('✅ All dependencies imported!')"
          python -c "import app, ai_agent, loader, plots, simulation, sidebar; print('✅ All modules imported!')" 